### ISSUE TITLE
BuildApp.js broken - buildCoreJS receives an invalid file list containing ',,' - an empty file

### ISSUE THREAD

**Issue by jlhughes** [foam-framework/foam#345]
buildCoreJS receives an invalid file list containing ',,' - an empty file. 

buildCoreJS aif(function() { file = ... }  console.log at line ~335 
file = myfiles[i++];  // log --> file[23]: ,function () { return __EXTRA_PROPERTIES__ != undefined; }

myfiles from line ~331 for my build.sh
myfiles: firefox,function () { return window.navigator && navigator.userAgent.indexOf('Firefox') != -1; },funcName,function () { return ! Number.name; },safari,function () { return window.navigator && navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1; },internetexplorer,function () { return ( window.Element && (!('remove' in Element.prototype))); },node,function IN_NODEJS() { return ! IN_BROWSER(); },i18n,function IN_BROWSER() { return typeof vm == "undefined" || ! vm.runInThisContext; },stdlib,WeakMap,function () { return ! this['WeakMap']; },async,parse,event,JSONUtil,XMLUtil,context,JSONParser,TemplateUtil,ChromeEval,function IN_CHROME_APP() { return window.chrome && window.chrome.runtime && (!! window.chrome.runtime.id) },FOAM,FObject,BootstrapModel,mm1Model,mm2Property,,function () { return __EXTRA_PROPERTIES__ != undefined; },mm3Types,mm4Method,mm5Debug,mm6Misc,../js/foam/core/bootstrap/OrDAO,../js/foam/core/bootstrap/BrowserFileDAO,function IN_BROWSER_NOT_APP() { return IN_BROWSER() && ! IN_CHROME_APP(); },../js/node/dao/ModelFileDAO,function IN_NODEJS() { return ! IN_BROWSER(); },../js/foam/ui/Window,value,view,../js/foam/ui/FoamTagView,cview,../js/foam/grammars/CSS3,HTMLParser,mlang,mlang1,mlang2,glang,QueryParser,oam,visitor,messaging,dao,arrayDAO,index,models,oauth,ModelDAO,function IN_BROWSER_NOT_APP() { return IN_BROWSER() && ! IN_CHROME_APP(); },../js/foam/core/bootstrap/ChromeAppFileDAO,function IN_CHROME_APP() { return window.chrome && window.chrome.runtime && (!! window.chrome.runtime.id) },ChromeAppModelDAO,function IN_CHROME_APP() { return window.chrome && window.chrome.runtime && (!! window.chrome.runtime.id) },NodeModelDAO,function IN_NODEJS() { return ! IN_BROWSER(); },../js/foam/u2/Element.js,../../../js/com/serviceecho/IntersectsExpr.js,../../../js/com/serviceecho/LteDateExpr.js,../../../js/com/serviceecho/LtDateExpr.js,../../../js/com/serviceecho/GteDateExpr.js,../../../js/com/serviceecho/GtDateExpr.js,../../../js/com/serviceecho/DateExprTrait.js,../../../js/com/serviceecho/ReferenceGroupByExpr.js,../../../js/com/serviceecho/SOQLAndExpr.js,../../../js/com/serviceecho/seutil.js

**Comment by adamvy** [comment]
Should be fixed with kevin's latest commit as of an hour ago.  I've verified that MBug is building successfully so your app should work too.

Sorry for the breakage, my fault.

**Comment by jlhughes** [comment]
Hi Adam
It's still broken; still receiving an invalid file list:
file[23]: ,function () { return __EXTRA_PROPERTIES__; }

my build.sh, perhaps it our config:

#!/bin/bash

SE_DIR=$PWD
FOAM_DIR=$SE_DIR/node_modules/foam
OUT_DIR=build

rm -rf $OUT_DIR
mkdir $OUT_DIR
node $FOAM_DIR/tools/foam.js foam.build.BuildApp targetPath=$SE_DIR/build \
     controller=com.serviceecho.WorkorderController \
     htmlFileName=junk.html \

 extraModels=foam.ui.md.FlatButton,foam.ui.ActionButton,foam.ui.KeyView,foam.ui.md.EditColumnsView,foam.ui.EditColumnsView
\
     extraClassPaths=$SE_DIR/js \

 extraFiles=../js/foam/u2/Element.js,../../../js/com/serviceecho/IntersectsExpr.js,../../../js/com/serviceecho/LteDateExpr.js,../../../js/com/serviceecho/LtDateExpr.js,../../../js/com/serviceecho/GteDateExpr.js,../../../js/com/serviceecho/GtDateExpr.js,../../../js/com/serviceecho/DateExprTrait.js,../../../js/com/serviceecho/ReferenceGroupByExpr.js,../../../js/com/serviceecho/SOQLAndExpr.js,../../../js/com/serviceecho/seutil.js

rm $OUT_DIR/junk.html
mv $OUT_DIR/foam.js $OUT_DIR/sefoam.js


Regards
Joel

**Comment by adamvy** [comment]
Innteresting.  Will get back to you shortly

**Comment by adamvy** [comment]
Ah, I forgot that MBug doesn't use the default file list, hence why it wasn't affected.

**Comment by adamvy** [comment]
Got it, try now.

**Comment by jlhughes** [comment]
Yep, that fixed it.
Thanks
Joel
